### PR TITLE
Fall 2016 Updates

### PR DESCRIPTION
**Pull request by joshukraine**
This update adds the following:
- Update all Q&A Booklets with new logo, various corrections
- Update all Answer Keys with new logo, various corrections
- Add "Downloads" link to main nav bar
- Remove outdated order form
- Minor wording updates

Before merging, we need to complete the following:
- [x] Update certificates (both Word and PDF) with new logo
- [x] Update intro letter with new logo
- [x] Update letterhead with new logo
- [x] Update printable invites with new logo
- [x] Update reminder letter (both Word and PDF) with new logo
- [x] Regenerate downloads zip file

### CODE REVIEW

**Comment by joshukraine** [comment]
@speedy1812 I just updated the printable invites PDF. However, I'm not sure if it's still interactive. I believe you set that up last time. :) Could you take a look? If needed, just make changes, save, and recommit.

**Comment by speedy1812** [comment]
Done, @joshukraine.

**Comment by joshukraine** [comment]
@speedy1812 Zip file updated. Could you please make sure it uncompresses ok on your machine? Thanks!

**Comment by speedy1812** [comment]
@joshukraine I think we are good to go. I looked over all the Q&A and Answer Key booklets, and they look good. I also noticed that there was a phantom Mac directory in the ZIP file, so I removed that.

**Pull request merged**
